on: [push]

jobs:
  build-and-publish-content:
    runs-on: ubuntu-latest
    name: Build and upload content to IBM Satellite
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
    - name: Upload to Satellite
      id: push
      uses: IBM/satellite-config-actions@alpha0.2
      with:
        apikey: ${{ secrets.apikey }}
        channel_id: 'a634d127-33d2-4854-82f6-6f4b82d46cd9'
        filename: 'namespace.yml'
    - name: Display the version_id
      run: echo "New version created ${{ steps.push.outputs.version_id }}"