on: [push]

jobs:
  build-and-publish-content:
    runs-on: ubuntu-latest
    name: Build and upload content to IBM Satellite
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
    - name: Lint k8s manifest files
      uses: Azure/k8s-lint@v1
      with:
        manifests: namespace.yml
        lintType: kubeval
    - name: Upload to Satellite
      id: push
      uses: IBM/satellite-config-actions@v1
      with:
        apikey: ${{ secrets.apikey }}
        channel_id: 'a634d127-33d2-4854-82f6-6f4b82d46cd9'
        filename: 'namespace.yml'
        version_name: ${{ github.run_number }}
    - name: Display the version_id
      run: env

