on: [push]

jobs:
  build_to_satellite:
    runs-on: ubuntu-latest
    name: Build and upload content to IBM Satellite
    steps:
    - name: Hello world action step
      id: push
      uses: IBM/satellite-config-actions@alpha1
      with:
        apikey: ''
        channel_id: ''
        filename: 'resource.yml'
    - name: Display the version_id
      run: echo "New version created ${{ steps.push.outputs.version_id }}"